# Site settings
author: Thomas Helin
title: OO Ruby CLI Project
header-img: img/home-bg.png
email: thomashelin@yahoo.com
copyright_name: Thomas Helin
description: > # this means to ignore newlines until "baseurl:"
  A Gem's Creation
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  torpedo-t

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
